/**
 * topics.ts
 *
 * A predefined list of broad topics for generating user-journey queries.
 */

export const topics: string[] = [
  "Video Games",
  "Healthcare",
  "Politics",
  "AI Advancements",
  "Climate Change",
  "Cybersecurity",
  "Space Exploration",
  "Renewable Energy",
  "Data Privacy",
  "Quantum Computing",
  "Automotive Innovations",
  "Fintech",
  "Blockchain",
  "Smart Home Technology",
  "Travel Destinations",
  "Cooking & Cuisine",
  "Fitness & Wellness",
  "Mental Health",
  "Educational Technology",
  "Online Marketing",
  "Personal Finance",
  "Real Estate",
  "Interior Design",
  "Fashion Trends",
  "Music and Entertainment",
  "Film Industry",
  "Environmental Conservation",
  "Public Health",
  "Gene Editing",
  "Pharmaceuticals",
  "Mobile App Development",
  "E-Commerce",
  "Digital Art",
  "Cryptocurrency",
  "3D Printing",
  "Drone Technology",
  "Virtual Reality",
  "Augmented Reality",
  "Robotics",
  "Ethical AI",
  "Social Media Trends",
  "Big Data",
  "Self-Driving Cars",
  "Language Learning",
  "Online Dating",
  "Pet Care",
  "Outdoor Activities",
  "Genealogy",
  "Solar Power",
  "Gardening"
];
